### ISSUE TITLE
[Go, Help Wanted] Find a cleaner way to implement User.Organization()

### ISSUE THREAD

**Issue by jahio** [joshsoftware/peerly#120]
In building the authentication system, of course I have to work with organizations a fair amount. Instead of embedding the Organization struct inside the User struct like I was doing, I instead implemented an Organization() function on *User. This way I can do something like:

```go
u, _ := deps.Store.GetUserByEmail(req.Context(), "some@email.com")
org, _ = u.Organization()
fmt.Printf("%+v\n", org)
```

The problem here is that I couldn't figure out how to define it on `*User` AND be able to use `*pgStore` to call/execute the GetOrganization function in the `db` package. **So I had to call Init() to get a `store` object that I could run `GetOrganization` on.**

I'm concerned that this is the wrong way to go about it, and the only reason I'm committing code with it in there is that (a) it works and (b) I don't know any better options. Additionally, calling `Init()` to do this could have side effects we're not thinking about or aware of as the code changes. Right now for example it forms a new connection to the database (which could have operations impacts) and logs that it's connected (which is going to make our logs a little confusing). What _else_ might it do that we don't account for in the future? What problems might this cause?

I'm looking for help with this one! I'd certainly like to hear from and work with a more experienced Gopher

**Comment by jahio** [comment]
Existing implementation as of May 12, 2020: https://github.com/joshsoftware/peerly/blob/login-flow/go-backend/db/user.go#L28

**Comment by PradipDKshirsagar** [comment]
@jahio You can pass the deps.Store to Organization method to access that *pgStore method.
i.e. u.Organization(deps.Store)

For implementation, you can refer:- https://github.com/joshsoftware/peerly/blob/core-values-apis/go-backend/db/core_value.go#L31

**Comment by jahio** [comment]
Hey Pradip,

It's funny you should mention this _now_ of all times, since Akshay, Anuj and I just had a Google Meet call and Anuj coached me through doing nearly this exact same thing! Instead of throwing deps at it, we passed deps.Storer instead so we could just call `store.GetOrganization(...)`. We also passed a context object with it so we could pass that on to the `db.GetOrganization()` method. [Here's a link to the commit](https://github.com/joshsoftware/peerly/commit/b36853b84a9b6ca1569e0ef79b7bce2eedd2d4a7) so you can see the diff.

Since we knocked this out (and rather easily with Anuj's help, thanks dude!) I'm going to close this issue. Stick a fork in it - it's DONE. 😃
