### ISSUE TITLE
PANIC: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by jahio** [joshsoftware/peerly#126]
I've just made [this commit](https://github.com/joshsoftware/peerly/commit/f67a2a2093b3845873be759a8df4b863f5403699) to the `session-mgmt-25` branch which dramatically cleans up the code and logic for issuing JWTs with successful logins. It also creates an `apperrors` package with methods and error objects for writing out JSON error messages to the API consumer.

Well, it works perfectly fine when you login to Google through a domain that exists (so an organization account) and is registered in our database. So your joshsoftware.com Google account should work just fine.

But I got to thinking: how about handling the error more gracefully when a user _doesn't_ have a domain registered to that account at all? I logged in with a bogus Google account that I have and instead of gracefully handling the error as you'd expect from the code, **the app panics and throws a memory address runtime error.**

Now, I'm not doing anything to play with memory addresses and my pointers seem totally normal as far as I can tell. And it only happens in _this specific case_. In fact, prior to adding code to handle that failure, everything still worked fine, it was just that the logged message and JSON error response were rather cryptic and unhelpful, so I implemented [lines 115-120 in service/session_http.go](https://github.com/joshsoftware/peerly/commit/f67a2a2093b3845873be759a8df4b863f5403699#diff-55d9b91c553c0b605f040702b91b9d9bR115-R120) to handle the error. It wasn't until that part - and only that part - was added that this bug happened.

The full stack trace:

```
PANIC: runtime error: invalid memory address or nil pointer dereference
goroutine 26 [running]:
github.com/urfave/negroni.(*Recovery).ServeHTTP.func1(0x291d3c8, 0xc0000b0118, 0xc00029c5f0, 0xc0000c6700)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/recovery.go:159 +0xcb
panic(0x15adbe0, 0x1b01e20)
	/Users/jah/.brew/Cellar/go/1.14.2_1/libexec/src/runtime/panic.go:969 +0x166
joshsoftware/peerly/apperrors.JSONError(0x291d3c8, 0xc0000b0118, 0x193, 0x0, 0x0)
	/Users/jah/Projects/peerly/go-backend/apperrors/apperrors.go:42 +0x43
joshsoftware/peerly/service.handleAuth.func1(0x291d3c8, 0xc0000b0118, 0xc0000c6900)
	/Users/jah/Projects/peerly/go-backend/service/session_http.go:119 +0x170d
net/http.HandlerFunc.ServeHTTP(0xc000288500, 0x291d3c8, 0xc0000b0118, 0xc0000c6900)
	/Users/jah/.brew/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0002c2000, 0x291d3c8, 0xc0000b0118, 0xc0000c6700)
	/Users/jah/.gopath/pkg/mod/github.com/gorilla/mux@v1.7.4/mux.go:210 +0xe2
github.com/urfave/negroni.Wrap.func1(0x291d3c8, 0xc0000b0118, 0xc0000c6700, 0xc0000a9e40)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:46 +0x4d
github.com/urfave/negroni.HandlerFunc.ServeHTTP(0xc000288cc0, 0x291d3c8, 0xc0000b0118, 0xc0000c6700, 0xc0000a9e40)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:29 +0x4e
github.com/urfave/negroni.middleware.ServeHTTP(0x1727e40, 0xc000288cc0, 0xc000288d40, 0x291d3c8, 0xc0000b0118, 0xc0000c6700)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Static).ServeHTTP(0xc0002836e0, 0x291d3c8, 0xc0000b0118, 0xc0000c6700, 0xc0000a9e20)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/static.go:53 +0x6dd
github.com/urfave/negroni.middleware.ServeHTTP(0x1726f40, 0xc0002836e0, 0xc000288d20, 0x291d3c8, 0xc0000b0118, 0xc0000c6700)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Logger).ServeHTTP(0xc000283170, 0x291d3c8, 0xc0000b0118, 0xc0000c6700, 0xc0000a9e00)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/logger.go:62 +0x8e
github.com/urfave/negroni.middleware.ServeHTTP(0x1726ee0, 0xc000283170, 0xc000288d00, 0x291d3c8, 0xc0000b0118, 0xc0000c6700)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Recovery).ServeHTTP(0xc00029c5f0, 0x291d3c8, 0xc0000b0118, 0xc0000c6700, 0xc0000a9de0)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/recovery.go:193 +0x8c
github.com/urfave/negroni.middleware.ServeHTTP(0x1726f20, 0xc00029c5f0, 0xc000288ce0, 0x291d3c8, 0xc0000b0118, 0xc0000c6700)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:38 +0x9c
github.com/urfave/negroni.(*Negroni).ServeHTTP(0xc000283740, 0x1731fe0, 0xc0001d0000, 0xc0000c6700)
	/Users/jah/.gopath/pkg/mod/github.com/urfave/negroni@v1.0.0/negroni.go:96 +0xeb
net/http.serverHandler.ServeHTTP(0xc0002ca0e0, 0x1731fe0, 0xc0001d0000, 0xc0000c6700)
	/Users/jah/.brew/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc000164780, 0x1733a20, 0xc0000d0fc0)
	/Users/jah/.brew/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/Users/jah/.brew/Cellar/go/1.14.2_1/libexec/src/net/http/server.go:2933 +0x35c
```

### Steps to Reproduce

1. Check out the `session-mgmt-25` branch and pull everything down.
1. Launch the server via `make server` or `go build && ./peerly start`. Make sure it's running on port 33001.
1. Go to https://accounts.google.com/o/oauth2/auth?client_id=749817093280-6h2emqcqsi84murdsdr543kuemvrlr9t.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A33001%2Fauth%2Fgoogle&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=state in your browser.
1. Login with a Google account that DOES NOT have a domain associated with it; so in other words, a personal account not part of an organization.
1. You'll be redirected to this app which will handle the request and (probably?) blow up with this memory bug.

**I could use some help with this problem.** I'm not sure what I'm doing wrong here, and I'm definitely confused. Maybe I have some kind of typo I'm not seeing or something? I don't know, everything looks right to me, so I could use some help from a more experienced Go developer.

...which is why I'm doing a cc here to @gautamrege and @iamanujvrma. You guys have more experience here and hopefully can help me out. Any advice would be appreciated. Thank you!

**Comment by iamanujvrma** [comment]
hey @jahio ,
Thanks for the detailed explanation. 

I found out the bug and here is how to debug this kind of bugs in future.

## Problem 

1. The log trace is huge but try to find out the lines which refer part of our code. In your case:
<img width="622" alt="Screenshot 2020-05-15 at 14 25 43" src="https://user-images.githubusercontent.com/16353963/82031775-f7469100-96b7-11ea-8360-b5d820dba432.png">

2. Then when I went to line in 119 (service/session_http.go) in [code](https://github.com/joshsoftware/peerly/blob/session-mgmt-25/go-backend/service/session_http.go#L119), I saw this:
<img width="929" alt="Screenshot 2020-05-15 at 14 26 20" src="https://user-images.githubusercontent.com/16353963/82031835-0d545180-96b8-11ea-80a6-7532ce87d692.png">

3. Here you are sending `err` to `ae.JSONError` method, but if you look closely the value of error is `nil` here. 
```
if len(user.Domain) < 3 { 
  // Shortest possible FQDN would be y.z
 log.Error(ae.ErrNoUserDomain, "No valid domain associated with user "+user.Email+" (domain: "+user.Domain+")", err)
 ae.JSONError(rw, http.StatusForbidden, err)
 return
}
```
There is no error being received from a method, you are just checking the condition that
```
if len(user.Domain) < 3 { 
```
so the value of `err` is nil

4. Now if we go to `ae.JSONError` function
<img width="823" alt="Screenshot 2020-05-15 at 14 30 55" src="https://user-images.githubusercontent.com/16353963/82032430-cf0b6200-96b8-11ea-9b2a-19e5ae69fc31.png">
you are trying to call `err.Error()`, since `err` is nil and we are trying to call method `Error` on nil, Go is throwing a panic.


## Solution
While checking the condition
```
if len(user.Domain) < 3 { 
 log.Error(ae.ErrNoUserDomain, "No valid domain associated with user "+user.Email+" (domain: "+user.Domain+")", err)
 ae.JSONError(rw, http.StatusForbidden, err)
 return
}
```

we have to manually set the error object like
```
err = errors.New("no valid domain associated with user")
```

or whatever error message you want. So the complete code block would look like this:

```
if len(user.Domain) < 3 { 
 err = errors.New("no valid domain associated with user")
 log.Error(ae.ErrNoUserDomain, "No valid domain associated with user "+user.Email+" (domain: "+user.Domain+")", err)
 ae.JSONError(rw, http.StatusForbidden, err)
 return
}

and the panic will go away
```

Let me know if this solves your problem

**Comment by jahio** [comment]
Wow, _this_ is how Go handles nil objects? Yikes. You're totally right with the bug in my code, I just didn't see it for some reason. Very easy to fix, no problem.

Is there a more graceful way to have Go handle such things in the future? A huge stack trace and panic because an object is nil, I mean...wow. Maybe it could catch that at compile time somehow?

Anyway, thanks a ton for your help!

**Comment by jahio** [comment]
Ok, got this fixed:

https://github.com/joshsoftware/peerly/commit/7fbb3efc6f9a6afc0065fb2fdd37c18f203546de

Thanks again, Anuj. Closing this out, it's done! 😃
