### ISSUE TITLE
[go backend] session_http.go tries to create user even if already in database

### ISSUE THREAD

**Issue by jahio** [joshsoftware/peerly#134]
## Problem
If you're an existing/valid user in the database, the login process still tries to create you anyway. Shouldn't be happening.

## Reproduce
1. Check out branch `session-mgmt-25`, get migrations run and `make server`
1. Have a user with your username/email (e.g. `j.austin.hughey@joshsoftware.com`) in your dev database
1. Initiate [peerly auth](https://accounts.google.com/o/oauth2/auth?client_id=749817093280-6h2emqcqsi84murdsdr543kuemvrlr9t.apps.googleusercontent.com&redirect_uri=http%3A%2F%2Flocalhost%3A33001%2Fauth%2Fgoogle&response_type=code&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&state=state)
1. Login w/ valid Josh Software account
1. Redirect will fire off code, give you a token, but you'll see this in the logs:

```
[negroni] 2020-05-18T11:40:17-06:00 | 403 | 	 603.687254ms | localhost:33001 | GET /auth/google
ERRO[18-05-2020 11:40:51] Error inserting user into database: j.austin.hughey@joshsoftware.com  err="pq: duplicate key value violates unique constraint \"users_email_unique_idx\""
ERRO[18-05-2020 11:40:51] Error commiting transaction inserting user into database: j.austin.hughey@joshsoftware.com  err="pq: Could not complete operation in a failed transaction"
```

## Solution

Initiate/fix a check on the `existingUser` variable before going forward. Right now around [line 127 in `service/session_http.go`](https://github.com/joshsoftware/peerly/blob/session-mgmt-25/go-backend/service/session_http.go#L127):

```go
		// See if there's an existing user that matches the oAuth user
		existingUser, err := deps.Store.GetUserByEmail(ctx, user.Email)
		if err != nil && err != sql.ErrNoRows {
			log.Error(ae.ErrUnknown, "Unknown/unexpected error while looking for existing user "+user.Email, err)
			ae.JSONError(rw, http.StatusInternalServerError, err)
			return
		} else {
```

Need to clean up that check with perhaps an elseif or another if statement.

Also, what's the correct way to check if a thing is nil in Go? We could just check for something like `if user.ID == 0 { ...` but that seems a bit...hacktastic. Then again maybe it's the way to do things in Go, I just don't know (yet).

**Comment by jahio** [comment]
Idea: Maybe we should implement something like `db.FindOrCreateDomain` and/or `db.FindOrCreateUser`, and rely on _those_ in this function. Something to ponder...

**Comment by the-spectator** [comment]
Proposal: How about returning `apperrors.RecordNotFound` error and then
```golang
existingUser, err := deps.Store.GetUserByEmail(ctx, user.Email)
if err == apperrors.RecordNotFound {
   db.CreateUser()
} else if err != nil {
  log.Error(...)
  return
}
```
Benifit I find in this approach is it more genric and now we have more actionable error.

**Comment by jahio** [comment]
I ended up doing something along those lines, @the-spectator. You can check out [this commit](https://github.com/joshsoftware/peerly/commit/d91654ccc3d955c87e06612a1ce88259a32615ba#diff-27f91d14ffef289100a15995594c12e5) to see exactly what. The important thing is this is now fixed. 😃
