### ISSUE TITLE
./peerly rollback appears broken

### ISSUE THREAD

**Issue by jahio** [joshsoftware/peerly#37]
```
$ panic: strconv.Atoi: parsing "": invalid syntax

goroutine 1 [running]:
main.main()
	/Users/jah/Projects/peerly/go-backend/main.go:62 +0x30d
```

Contents of DB migrations dir:

```
$ ls migrations/
Permissions Size User Date Modified Git Name
.rw-r--r--     0 jah  21 Apr  4:46   -- .keep
.rw-r--r--    18 jah  21 Apr  5:07   -- 1587381324_create_users.down.sql
.rw-r--r--   792 jah  21 Apr  5:06   -M 1587381324_create_users.up.sql
```

Contents of `1587381324_create_users.down.sql`:

```sql
DROP TABLE users;
```

**Comment by iamanujvrma** [comment]
Hi Austin,

Thanks for reporting this
However its not broken, its just that the command usage description is not correct . The correct  way to use the command is as below:

```
./peerly rollback [steps (int) ]

for eg:

./peerly rollback 1
```
I will update the command usage. Thanks again.

**Comment by jahio** [comment]
D'oh, sorry about that, looks like it was an "Error 18": the error was 18 inches from the screen.
